FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

COPY ./apps/web ./apps/web

RUN npm i -g pnpm
RUN pnpm install

RUN pnpm run generate:db
RUN export DATABASE_URL=${DATABASE_URL} && pnpm run build

EXPOSE 3000

CMD [ "pnpm", "run", "start:fe" ]
